import {Timer} from 'lucide-react';
import Link from 'next/link';
import Shell from '@/components/Shell';
import JournalLatencyPage from '@/components/JournalLatencyPage';
import FileAnalyticsControls from '@/components/FileAnalyticsControls';
import LatencyTrend from '@/components/LatencyTrend';
import LatencySessionControls from '@/components/LatencySessionControls';
import { sessionQuery } from '@/lib/latency-dashboard';
import StageTiming from '@/components/StageTiming';
import {PageHead,EmptyState,KpiCard} from '@/components/UI';
import {getJSON,apiError} from '@/lib/api';
import {fileQuery,metric,type FileQuery} from '@/lib/file-analytics';
export const dynamic='force-dynamic';
export default async function Page({searchParams}:{searchParams:Promise<FileQuery>}) {
 let q=await searchParams;let d:any=await getJSON(`/api/files/latency?${fileQuery(q)}`);
 // The legacy journal view remains available when CSV analytics is unconfigured.
 if(d._status===503){const config:any=await getJSON('/api/config');if(config.csv_configured===false && !config.analytics_database_configured)return <JournalLatencyPage/>;}
 if(!apiError(d) && !q.start && !q.end && d.trade_dates?.[0]) { q=Object.fromEntries(new URLSearchParams(sessionQuery(q,d.trade_dates[0],'00:00','23:59'))); d=await getJSON(`/api/files/latency?${fileQuery(q)}`); }
 const error=apiError(d),s=d.summary||{},limit=Number(q.limit||50),offset=Number(q.offset||0),unit=d.unit||'source units';
 return <Shell><PageHead title="OMS latency analytics" subtitle="Processing and exchange confirmation observations · historical imported observations" badge="FILE-BASED" badgeTone="warn"/>
 {error?<EmptyState title="Unable to load latency analytics" body={`${error}. Retry when the source service is available.`}/>:<>
 <div className="file-context"><span><b>{metric(d.count)}</b> matching events · <b>{metric(d.unique_orders)}</b> unique orders</span><Link href="/data-quality">Source health & ingestion →</Link></div>
 <LatencySessionControls key={`session-${fileQuery(q)}`} query={q} dates={d.trade_dates||[]}/>
 <FileAnalyticsControls key={fileQuery(q)} query={q} facets={{segments:d.choices?.segment||[],statuses:d.facets?.statuses||[]}}/>
 <section className="kpi-grid latency-kpis">{[['OMS p50',s.oms?.p50],['OMS mean',s.oms?.mean],['OMS p95',s.oms?.p95],['OMS maximum',s.oms?.max],['Confirmation p50',s.confirmation?.p50]].map(([name,value])=><KpiCard icon={<Timer size={18}/>} key={String(name)} label={`${name} (${unit})`} value={metric(value as number)} sub="Measured samples in selected range" tone="blue"/>)}<KpiCard icon={<Timer size={18}/>} label="Recorded events" value={metric(d.count)} sub={`${metric(d.unique_orders)} unique orders`}/></section>
 <section className="panel"><div className="panel-head"><b>Latency distribution</b><span>Same filters as the event table and export</span></div><div className="table-scroll" tabIndex={0} aria-label="Latency percentile comparison"><table className="orders-table"><thead><tr><th>Measurement ({unit})</th><th>Valid samples</th>{['p50','p90','p95','p99','max'].map(p=><th key={p}>{p}</th>)}</tr></thead><tbody>{[['oms','OMS processing'],['confirmation','Reported exchange confirmation']].map(([key,name])=><tr key={key}><td>{name}</td><td>{metric(s[key]?.samples)}</td>{['p50','p90','p95','p99','max'].map(p=><td key={p}>{metric(s[key]?.[p])}</td>)}</tr>)}</tbody></table></div></section>
 <section className="panel"><div className="panel-head"><b>OMS processing latency</b><span>{d.bucket_seconds}-second buckets · Asia/Kolkata</span></div><LatencyTrend label="OMS latency" unit={unit} series={[{key:'p50',label:'p50',color:'var(--signal)'},{key:'mean',label:'Mean',color:'var(--ink)'},{key:'max',label:'Maximum',color:'var(--red)'}]} points={(d.trend||[]).map((r:any)=>({time:r.time,p50:r.oms_stats?.p50,mean:r.oms,max:r.oms_stats?.max}))}/></section>
 <section className="panel"><div className="panel-head"><b>Recorded volume per bucket</b><span>Events, not unique orders</span></div><LatencyTrend label="Event volume" unit="events" series={[{key:'count',label:'Events',color:'var(--signal)'}]} points={d.trend||[]}/></section>
 <section className="panel"><div className="panel-head"><b>Reported exchange confirmation</b><span>Outliers remain visible</span></div><LatencyTrend label="Exchange confirmation timing" unit={unit} series={[{key:'mean',label:'Mean',color:'var(--signal)'},{key:'max',label:'Maximum',color:'var(--red)'}]} points={(d.trend||[]).map((r:any)=>({time:r.time,mean:r.confirmation,max:r.confirmation_stats?.max}))}/></section>
 <section className="latency-segments">{(d.by_segment||[]).map((r:any)=><article className="panel" key={r.segment}><div className="panel-head"><b>{r.segment}</b><span>{metric(r.count)} events</span></div><dl className="latency-segment-stats">{[['OMS p50',r.oms?.p50],['OMS mean',r.oms?.mean],['OMS p95',r.oms?.p95],['OMS p99',r.oms?.p99],['OMS maximum',r.oms?.max],['Confirmation p50',r.confirmation?.p50]].map(([name,value])=><div key={String(name)}><dt>{name} ({unit})</dt><dd>{metric(value as number)}</dd></div>)}</dl></article>)}</section>
 <section className="panel"><div className="panel-head"><b>OMS latency histogram</b><span>{metric(s.oms?.samples)} valid samples · {unit}</span></div><div className="latency-histogram">{(d.histogram||[]).map((r:any)=>{const percent=s.oms?.samples?100*r.count/s.oms.samples:0;return <div key={r.lower}><span>{r.upper===null?`${metric(r.lower)}+`:`${metric(r.lower)}–${metric(r.upper)}`}</span><div><i style={{width:`${percent}%`}}/></div><b>{metric(r.count)} <small>({metric(percent)}%)</small></b></div>;})}</div><p className="chart-caption">Lower bound inclusive, upper bound exclusive. Missing measurements are excluded. Units follow the configured source contract.</p></section>
 <section className="panel"><div className="panel-head"><b>Latency by exchange segment</b><span>Every value uses the selected filters</span></div><div className="table-scroll" tabIndex={0} aria-label="Segment latency comparison"><table className="orders-table"><thead><tr><th>Segment</th><th>Events</th><th>Valid OMS samples</th>{['p50','mean','p95','p99','max'].map(k=><th key={k}>OMS {k} ({unit})</th>)}<th>Confirmation p50 ({unit})</th></tr></thead><tbody>{(d.by_segment||[]).map((r:any)=><tr key={r.segment}><td>{r.segment}</td><td>{metric(r.count)}</td><td>{metric(r.oms?.samples)}</td>{['p50','mean','p95','p99','max'].map(k=><td key={k}>{metric(r.oms?.[k])}</td>)}<td>{metric(r.confirmation?.p50)}</td></tr>)}</tbody></table></div></section>
 <StageTiming query={q}/>
 <section className="panel"><div className="panel-head"><b>Event evidence</b><a className="btn" href={`/api/exports/latency?${fileQuery(q,{limit:'',offset:''})}`}>Export all matching rows</a></div>
 <div className="table-scroll" tabIndex={0} aria-label="Scrollable latency events"><table className="orders-table"><thead><tr><th>Order</th><th>Segment</th><th>Event time (UTC)</th><th>OMS ({unit})</th><th>Confirmation ({unit})</th><th>OMS status</th><th>Source file</th></tr></thead><tbody>{(d.items||[]).map((r:any)=><tr key={`${r.file}:${r.fingerprint}`}><td><Link href={`/orders?order=${encodeURIComponent(r.order_id)}`}>{r.order_id}</Link></td><td>{r.segment}</td><td>{r.event_time?.replace('T',' ').replace('+00:00','')}</td><td>{metric(r.oms)}</td><td>{metric(r.confirmation)}</td><td>{r.oms_status??'Not supplied'}</td><td>{r.file}</td></tr>)}</tbody></table></div>
 {!d.count&&<EmptyState title="No matching events" body="Widen the time range or reset your filters."/>}
 <div className="table-foot"><span role="status">{d.count?offset+1:0}–{Math.min(offset+limit,d.count)} of {metric(d.count)} matching events</span><div className="grid-pagination">{offset>0&&<Link className="btn" href={`?${fileQuery(q,{offset:String(Math.max(0,offset-limit))})}`}>Previous page</Link>}{offset+limit<d.count&&<Link className="btn" href={`?${fileQuery(q,{offset:String(offset+limit)})}`}>Next page</Link>}</div></div></section>
 <details className="panel latency-notes"><summary>Source details and interpretation</summary><p className="chart-caption">Historical CSV snapshot · {unit} · {d.bucket_seconds}-second buckets. Missing measurements remain unavailable. Chart times use IST; evidence timestamps below use UTC.</p><ul className="config-list">{(d.notes?.length?d.notes:(d.note?[d.note]:[])).map((n:string)=><li key={n}>{n}</li>)}</ul></details>
 </>}</Shell>;
}
