export const SESSION_JOURNAL_FIELDS = [
  "Record No.",
  "Event Time (UTC)",
  "NorenTimeStamp",
  "NorenNsecs",
  "msg_type",
  "UserId",
  "Seqno",
  "msg_seq",
  "AccessType",
  "AddlSrcInfoes",
  "DevicePinFlag",
  "LastAttemptCount",
  "LoginProcId",
  "Msg",
  "Question2fas",
  "ReqStatus",
  "UiDevCode",
  "UserPrivilege",
  "UserSessId",
  "Userdetails.AcctIds",
  "Userdetails.AcctOverview",
  "Userdetails.BrokerId",
  "Userdetails.DisplayPrecision",
  "Userdetails.Dob",
  "Userdetails.EmailId",
  "Userdetails.LastAttemptCount",
  "Userdetails.LastLoginIp",
  "Userdetails.LastLoginMac",
  "Userdetails.LastLoginTime",
  "Userdetails.LastPasswordTime",
  "Userdetails.Login2faDatas",
  "Userdetails.MaxContractSub",
  "Userdetails.MobNum",
  "Userdetails.NorenAppVersion",
  "Userdetails.PasswordReset",
  "Userdetails.PrevPasswords",
  "Userdetails.Products",
  "Userdetails.PropOrdFlag",
  "Userdetails.RedSuperUser",
  "Userdetails.Region",
  "Userdetails.User2faDetails",
  "Userdetails.UserAccessGrp",
  "Userdetails.UserAccessTypes",
  "Userdetails.UserDpinDetails",
  "Userdetails.UserExchDetails",
  "Userdetails.UserId",
  "Userdetails.UserIpAddr",
  "Userdetails.UserMacAddr",
  "Userdetails.UserMws",
  "Userdetails.UserName",
  "Userdetails.UserOrdTypes",
  "Userdetails.UserPrivilege",
  "Userdetails.UserSessId",
  "Userdetails.UserSessOtp",
  "Userdetails.UserTag"
] as const;
export const LOGOUT_JOURNAL_FIELDS = [
  "Record No.",
  "Event Time (UTC)",
  "NorenTimeStamp",
  "NorenNsecs",
  "msg_type",
  "UserId",
  "Seqno",
  "msg_seq",
  "AccessType",
  "AddlSrcInfoes",
  "LoginProcId",
  "Question2fas",
  "ReqStatus",
  "UserPrivilege",
  "UserSessId",
  "Userdetails.AcctIds",
  "Userdetails.BrokerId",
  "Userdetails.Login2faDatas",
  "Userdetails.PrevPasswords",
  "Userdetails.Products",
  "Userdetails.User2faDetails",
  "Userdetails.UserAccessTypes",
  "Userdetails.UserDpinDetails",
  "Userdetails.UserExchDetails",
  "Userdetails.UserId",
  "Userdetails.UserMws",
  "Userdetails.UserOrdTypes"
] as const;
export function sessionFieldText(value: unknown): string {
 if (value == null || value === "") return "—";
 return typeof value === "object" ? JSON.stringify(value) : String(value);
}
